apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex-rule-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cortex-rule-watcher
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cortex-rule-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cortex-rule-watcher
subjects:
  - kind: ServiceAccount
    name: cortex-rule-watcher
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-rule-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-rule-watcher
  template:
    metadata:
      labels:
        app: cortex-rule-watcher
    spec:
      serviceAccountName: cortex-rule-watcher
      containers:
        - name: cortex-rule-watcher
          args:
            - --rule-path=/local-rules
          image: slamdev/cortex-rule-watcher:latest
          imagePullPolicy: Always
          ports:
            - name: http-health
              containerPort: 8081
            - name: http-metrics
              containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
          volumeMounts:
            - name: rules
              mountPath: /local-rules
        - name: ruler
          args:
            - -target=ruler
            - -auth.multitenancy-enabled=false
            - -ruler.poll-interval=5s
            - -ruler-storage.backend=local
            - -ruler-storage.local.directory=/local-rules
          image: grafana/mimir:2.0.0
          ports:
            - name: http-metrics
              containerPort: 8080
            - name: grpc
              containerPort: 9095
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: rules
              mountPath: /local-rules/fake
      volumes:
        - name: rules
          emptyDir: { }
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cortex-rule-watcher
spec:
  groups:
    - name: rules
      rules:
        - expr: |-
            up
          record: cortex_rule_watcher5:up
